/**
 * Dedicated industry benchmarking profiles, rankings, and workflow data.
 */

export const INDUSTRIES = {
  'manufacturing-distribution': {
    slug: 'manufacturing-distribution',
    name: 'Manufacturing & Wholesale Distribution',
    shortName: 'Manufacturing',
    title: 'Best AI Sales Tools for Manufacturing (2026)',
    description: 'Compare top AI sales tools for manufacturing and wholesale distribution. Benchmark ERP integration, stock checks, and CPQ quote speed.',
    heroSummary: 'Manufacturing and industrial distribution teams lose hours daily toggling between CRM records and ERP databases (SAP, Oracle, Dynamics, Infor). The leading platforms for this sector connect directly with enterprise data models, manage complex tiered contract pricing, and automate quote generation across sales and operations.',
    bottleneck: 'ERP data fragmentation, complex tiered contract pricing, inventory visibility, and slow quote generation.',
    topPick: 'Salesforce Agentforce & SAP Joule',
    rankings: [
      {
        rank: 1,
        name: 'Salesforce Agentforce',
        url: 'https://salesforce.com/agentforce',
        type: 'CRM-Native Autonomous Agent',
        pricing: '$500 per 100k Flex Credits + Enterprise seat fees',
        erpSupport: 'Via MuleSoft & Salesforce Data Cloud',
        bestFor: 'Large enterprises whose manufacturing data is fully replicated in Salesforce Data Cloud',
        winReason: 'Deep integration with Salesforce Data Cloud, automated Flow actions, and native enterprise CRM capabilities across multi-tier accounts.',
        skipIf: 'You want fixed transaction pricing or have ERP data outside the Salesforce ecosystem.',
      },
      {
        rank: 2,
        name: 'SAP Joule',
        url: 'https://www.sap.com/products/artificial-intelligence/joule.html',
        type: 'Native ERP Copilot',
        pricing: 'Bundled in SAP S/4HANA Cloud Editions',
        erpSupport: 'Native inside S/4HANA Cloud Public & Private',
        bestFor: 'Manufacturing enterprises running core operations natively on SAP S/4HANA',
        winReason: 'Operates natively inside SAP without requiring third-party API connectors, data replication, or custom integration pipelines.',
        skipIf: 'Your CRM and sales workflows live entirely outside SAP.',
      },
      {
        rank: 3,
        name: 'Salezx',
        url: 'https://www.salezx.com',
        type: 'AI Sales Brain for Microsoft Teams & ERP',
        pricing: 'AI Transactions (Walk, Run & Drive plans; e.g. Drive 25-user at ₹8.6L/yr, unlimited seats)',
        erpSupport: 'Structured ERP reports & data extracts (no pre-built vendor connectors published)',
        bestFor: '2-second account briefings, live stock checks, custom tiered pricing & margin protection in MS Teams',
        winReason: 'Functions as a conversational sales assistant across CRM documents and uploaded ERP reports inside Microsoft Teams without per-seat licensing penalties.',
        skipIf: 'You require purely cold outbound email scraping, native zero-config SAP API connectors, or do not use Microsoft 365.',
      },
      {
        rank: 4,
        name: '11x',
        url: 'https://11x.ai',
        type: 'Autonomous Outbound SDR',
        pricing: 'Quote-based ($100,000+/yr)',
        erpSupport: 'None (Outbound only)',
        bestFor: 'Targeting new industrial equipment procurement buyers in untapped regions',
        winReason: 'Autonomous multichannel outreach across phone, WhatsApp, and email.',
        skipIf: 'Your focus is servicing existing distributor accounts or quoting active orders.',
      },
    ],
    challenges: [
      {
        title: 'The ERP-CRM Visibility Void',
        detail: 'Sales reps quote stale prices or commit to unavailable delivery dates because inventory numbers live locked inside on-premise or cloud ERP systems.',
      },
      {
        title: 'Per-Seat Software Inflation',
        detail: 'Distributors employ large teams of inside reps, field reps, and customer service agents. Per-seat AI pricing models make full-company AI rollout prohibitively expensive.',
      },
      {
        title: 'Complex Multi-Catalogue Quoting',
        detail: 'Industrial buyers order across hundreds of SKUs with negotiated customer discounts that generic chatbots cannot compute.',
      },
    ],
  },

  'b2b-saas': {
    slug: 'b2b-saas',
    name: 'B2B SaaS & Tech Startups',
    shortName: 'B2B SaaS',
    title: 'Best AI Sales Agents for B2B SaaS (2026)',
    description: 'Compare top AI SDRs and sales copilots for B2B SaaS. Benchmark 11x, Artisan, Clay, and Qualified on multichannel outreach and pipeline generation.',
    heroSummary: 'B2B SaaS companies require high-volume, highly personalized top-of-funnel outbound combined with intelligent deal execution. Autonomous SDRs like 11x and Artisan lead cold outreach, while Clay provides the data waterfall and Qualified converts inbound traffic.',
    bottleneck: 'Empty top-of-funnel pipeline, declining cold email reply rates, and long technical demo cycles.',
    topPick: '11x & Artisan',
    rankings: [
      {
        rank: 1,
        name: '11x',
        url: 'https://11x.ai',
        type: 'Autonomous Multi-Channel SDR',
        pricing: 'Quote-based ($100,000+/yr)',
        erpSupport: 'Not applicable',
        bestFor: 'High-TAM software companies needing automated voice, WhatsApp & email outreach',
        winReason: 'Alice and Julian digital workers provide genuine phone calling, LinkedIn automation, and autonomous calendar booking.',
        skipIf: 'Your TAM is narrow or your team cannot invest 90 days into prompt and list calibration.',
      },
      {
        rank: 2,
        name: 'Artisan',
        url: 'https://artisan.co',
        type: 'Autonomous Outbound SDR',
        pricing: 'Quote-based ($2,000–$5,000/mo)',
        erpSupport: 'Not applicable',
        bestFor: 'Consolidated B2B data, email warm-up, and LinkedIn prospecting',
        winReason: 'Ava combines 300M+ B2B contact records with modern sequence building in a streamlined interface.',
        skipIf: 'You require phone calling or multi-language voice AI outreach.',
      },
      {
        rank: 3,
        name: 'Clay',
        url: 'https://clay.com',
        type: 'Data Orchestration & Waterfall',
        pricing: 'Usage-based credit tiers',
        erpSupport: 'Not applicable',
        bestFor: 'Deep account enrichment from 75+ data providers before launching sequences',
        winReason: 'The industry benchmark for building bespoke account research tables and scraping live signals.',
        skipIf: 'You want an all-in-one sending agent rather than a data workbench.',
      },
      {
        rank: 4,
        name: 'Qualified',
        url: 'https://qualified.com',
        type: 'Inbound Pipeline Agent',
        pricing: 'Annual contract ($40k+/yr)',
        erpSupport: 'Not applicable',
        bestFor: 'Real-time website visitor intent scoring and instant meeting scheduling',
        winReason: 'Piper AI agent engages high-intent buyers on SaaS websites and books sales calls in real time.',
        skipIf: 'You only need outbound cold prospecting.',
      },
    ],
    challenges: [
      {
        title: 'The Inbox Saturation Crisis',
        detail: 'Cold email deliverability is at historic lows as spam filters penalize generic AI templates. Multichannel outreach (voice, LinkedIn) is mandatory.',
      },
      {
        title: 'Technical Objection Handling',
        detail: 'SaaS buyers ask nuanced API, security, and integration questions on calls that junior SDRs cannot navigate alone.',
      },
      {
        title: 'Tool Sprawl & Cost',
        detail: 'Stacking separate tools for data, warming, sequencer, phone, and CRM adds up to thousands per rep monthly.',
      },
    ],
  },

  'professional-services': {
    slug: 'professional-services',
    name: 'Professional Services & Consulting',
    shortName: 'Professional Services',
    title: 'AI Sales Tools for Professional Services (2026)',
    description: 'Compare the best AI sales tools for consulting, legal, and advisory firms. Ranked by document synthesis, confidentiality, and proposal speed.',
    heroSummary: 'Consulting, legal, and advisory firms win business through relationship context and customized proposals. Microsoft Copilot and Salezx lead professional services by automating client meeting follow-ups, proposal drafting, and securely indexing SharePoint decks with strict enterprise governance.',
    bottleneck: 'Slow proposal drafting, lost institutional knowledge from past engagements, and strict client data confidentiality.',
    topPick: 'Microsoft Copilot',
    rankings: [
      {
        rank: 1,
        name: 'Microsoft Copilot for Sales',
        url: 'https://www.microsoft.com/en-us/microsoft-365/enterprise/copilot-for-sales',
        type: 'Office 365 & Teams Workflow Copilot',
        pricing: '$50/user/month add-on',
        erpSupport: 'Microsoft Dynamics 365 & Power Platform',
        bestFor: 'Meeting summaries, Outlook drafting & client relationship notes in Teams',
        winReason: 'Directly embedded inside Microsoft 365 Outlook, Teams, and PowerPoint where consultants live daily, creating instant meeting briefs and CRM summaries.',
        skipIf: 'You run a non-Microsoft stack or want usage-based billing rather than per-seat licensing.',
      },
      {
        rank: 2,
        name: 'Salezx',
        url: 'https://www.salezx.com',
        type: 'Knowledge & CRM Copilot',
        pricing: 'AI Transactions (Walk, Run & Drive plans; unlimited team users)',
        erpSupport: 'Project accounting & CRM integration',
        bestFor: 'Instant RFP drafting, past project retrieval, and client briefing in MS Teams',
        winReason: 'Indexes Microsoft 365 SharePoint decks, past proposal files, and billing data with zero data leakage. Partners and consultants get instant pre-meeting briefs.',
        skipIf: 'You run a Google Workspace-only firm or need cold consumer outreach.',
      },
      {
        rank: 3,
        name: 'Clay',
        url: 'https://clay.com',
        type: 'Relationship & Network Mapping',
        pricing: 'Usage-based',
        erpSupport: 'Not applicable',
        bestFor: 'Mapping executive alumni networks and corporate board affiliations',
        winReason: 'Enriches C-level target lists with executive transitions and funding events.',
        skipIf: 'You need document retrieval and internal proposal assistance.',
      },
      {
        rank: 4,
        name: 'Salesforce Agentforce',
        url: 'https://salesforce.com/agentforce',
        type: 'CRM Workflow Automation',
        pricing: '$500 per 100k credits + per-seat licences',
        erpSupport: 'Via FinancialForce / Certinia',
        bestFor: 'Large advisory firms built entirely on the Salesforce Financial Services Cloud',
        winReason: 'Automates client onboarding flows and compliance logging.',
        skipIf: 'You require lightweight Microsoft Teams-native document assistance.',
      },
    ],
    challenges: [
      {
        title: 'Information Silos Across Practice Areas',
        detail: 'Valuable case studies and proposal decks remain locked in individual partner drives rather than shared across the firm.',
      },
      {
        title: 'Client Data Confidentiality',
        detail: 'Firms cannot feed confidential client documents into public LLMs without risking contractual breaches.',
      },
      {
        title: 'Partner Billable Hour Drag',
        detail: 'Senior partners spend 15+ hours weekly researching background context and formatting proposals rather than billing clients.',
      },
    ],
  },

  'healthcare-medtech': {
    slug: 'healthcare-medtech',
    name: 'Healthcare, MedTech & Life Sciences',
    shortName: 'Healthcare & MedTech',
    title: 'AI Sales Tools for Healthcare & MedTech (2026)',
    description: 'Rankings of AI sales tools for medical device and healthcare teams. Benchmark HIPAA compliance, catalogue lookup, and hospital RFP support.',
    heroSummary: 'Medical device and healthcare sales involve complex regulatory catalogues, hospital procurement committees, and strict compliance boundaries. Salesforce Agentforce leads enterprise healthcare with audited HIPAA compliance and Health Cloud integrations, while Salezx assists field reps with instant catalogue specs.',
    bottleneck: 'Strict regulatory compliance, complex hospital RFP requirements, and extensive clinical product specifications.',
    topPick: 'Salesforce Agentforce',
    rankings: [
      {
        rank: 1,
        name: 'Salesforce Agentforce Life Sciences',
        url: 'https://salesforce.com/agentforce',
        type: 'Life Sciences Cloud Agent',
        pricing: '$500 per 100k Flex Credits',
        erpSupport: 'Enterprise Health Cloud integration',
        bestFor: 'Pharmaceutical key account management, Health Cloud workflows, and HIPAA compliance',
        winReason: 'Built directly onto Salesforce Life Sciences Cloud with audited healthcare compliance controls, patient data safeguards, and automated territory logging.',
        skipIf: 'You require simple, fast deployment outside the Salesforce ecosystem.',
      },
      {
        rank: 2,
        name: 'Salezx',
        url: 'https://www.salezx.com',
        type: 'Enterprise Copilot & Catalogue Assistant',
        pricing: 'AI Transactions (Walk, Run & Drive plans; unlimited team users)',
        erpSupport: 'Medical ERP & CRM connectors',
        bestFor: 'Field reps answering clinical specs, hospital contract pricing & compliance verification',
        winReason: 'Strict read-only guardrails guarantee clinical documents are never altered or trained upon. Field reps retrieve precise device specs and hospital contract terms in seconds.',
        skipIf: 'You need mass unverified outbound cold email blasting.',
      },
      {
        rank: 3,
        name: 'Qualified',
        url: 'https://qualified.com',
        type: 'Inbound Healthcare Lead Qualifier',
        pricing: 'Quote-based',
        erpSupport: 'Not applicable',
        bestFor: 'Routing healthcare provider inquiries on medical software websites',
        winReason: 'Real-time qualification for physician and hospital administrator web traffic.',
        skipIf: 'Your sales motion is 100% field-based and offline.',
      },
    ],
    challenges: [
      {
        title: 'Regulatory & Compliance Guardrails',
        detail: 'Every piece of product collateral and clinical claim must adhere strictly to approved regulatory language.',
      },
      {
        title: 'Hospital Group Purchasing (GPO) Pricing',
        detail: 'Pricing varies wildly across health systems, IDNs, and GPO contracts, requiring instant ERP tier lookup.',
      },
      {
        title: 'Field Rep Mobility',
        detail: 'MedTech reps spend their days in hospitals and surgical suites, needing instant answers via mobile messaging tools like Teams.',
      },
    ],
  },
}

export function getIndustry(slug) {
  return INDUSTRIES[slug] || null
}

export function getAllIndustries() {
  return Object.values(INDUSTRIES)
}
